const smc_errors = {
    0: `No error`,
    1: `Communication error. The fieldbus slave is no longer in state operational.`,
    2: `Axis error`,
    3: `Fieldbus has lost synchronicity`,
    10: `Position outside of permissible range of SWLimit`,
    11: `Hardware end switch is active`,
    12: `This error occurs if a linear axis has more than 2^15 32-bit overflows of the position in increments`,
    13: `Drive status Halt or Quickstop is not supported`,
    14: `Drive has no power`,
    15: `This error is no longer used`,
    16: `Position lag error. Difference between set and current position exceeds the given limit`,
    17: `Homing error reported by axis`,
    18: `A problem with the license occurred`,
    20: `Controller enable not done or brake applied`,
    21: `Axis in wrong controller mode`,
    25: `Invalid action at logical axis`,
    30: `Motion creating module has not been called again before end of the motion`,
    31: `Type of given AXIS_REF variable is not AXIS_REF`,
    32: `AXIS_REF variable has been exchanged while the module was active.`,
    33: `Axis disabled while being moved. MC_Power.bRegulatorOn`,
    34: `Axis in its current state cannot execute a motion command, because the axis doesn’t signal currently that it follows the target values.`,
    35: `The drive reported an error during an ongoing movement.`,
    40: `Maximum velocity fMaxVelocity exceeded`,
    41: `Maximum acceleration fMaxAcceleration exceeded`,
    42: `Maximum deceleration fMaxDeceleration exceeded`,
    50: `Invalid velocity or acceleration values`,
    51: `Mode requests for safety reasons use of end switches.`,
    60: `No free handle has been sent to open file.`,
    65: `Initialization of SMC_MultiAcyclicCommunicator not successful`,
    66: `The axis has got an invalid handle`,
    67: `Too many tasks with SDO-producing axes`,
    68: `Atomic add failed`,
    69: `SDO-read lead to invalid datalength (> 4)`,
    70: `Mode not supported`,
    71: `In current mode, controller mode cannot be changed.`,
    72: `SMC_SetControllerMode has been interrupted by MC_Stop or errorstop.`,
    75: `Axis not in correct controller mode. Deprecated, no longer returned by SMC_SetTorque.`,
    80: `Error at startup of the axis group`,
    81: `The axis is not yet in the required state.`,
    85: `The function block does not support virtual or logical axes.`,
    86: `The number of absolute bits is invalid, must be in the range 8 .. 32.`,
    90: `Invalid values`,
    91: `Gearing parameters must not be changed as long as the drive is under control.`,
    92: `Invalid modulo period (<= 0 or greater than half the bus bandwidth)`,
    93: `The modulo period in increments is not an integer, but the modulo-handling is done by the drive.`,
    110: `Axis contain no information on cycle time (fTaskCycle = 0).`,
    120: `Axis without error`,
    121: `Axis does not perform error-reset.`,
    122: `Error could not be reset.`,
    123: `Communication with the axis did not work.`,
    124: `If there is communication error, it cannot be reset`,
    130: `Parameter number unknown`,
    131: `Error during transmission to the drives. See error number in function block instance ReadDriveParameter.`,
    132: `No assignment for drive parameters available`,
    133: `Conversion of the value to / from the drive parameters failed.`,
    140: `Parameter number unknown or writing not allowed`,
    141: `See error number in function block instance WriteDriveParameter`,
    142: `No assignment for drive parameters available`,
    143: `Conversion of the value to / from the drive parameters failed.`,
    170: `Axis was not in standstill state.`,
    171: `Drive did not start homing.`,
    172: `Drive did not reply, when homing was done.`,
    173: `Error at stop after homing. Deceleration may not be set.`,
    174: `Drive is in errorstop status. Homing cannot be executed.`,
    180: `Unknown error at stop`,
    181: `Invalid velocity or acceleration values`,
    182: `Direction = shortest not applicable`,
    183: `Drive is in errorstop status. Stop cannot be executed`,
    184: `Instance of MC_Stop blocking the axis by Execute = TRUE has not been called yet. MC_Stop (Execute = FALSE) has to be called.`,
    185: `Cannot interrupt an ongoing MC_Stop`,
    200: `The task interval of the bus task could not be determined.`,
    201: `Invalid velocity or acceleration values`,
    202: `Direction error`,
    226: `Invalid velocity or acceleration values`,
    227: `Direction error`,
    251: `Invalid velocity or acceleration values`,
    252: `Direction error`,
    276: `Invalid velocity or acceleration values`,
    277: `Direction error`,
    278: `Except from aborting, don’t call a major mvt-FB after SMC_MoveSuperimposed`,
    300: `No longer used; only for compatibility`,
    301: `Invalid velocity or acceleration values`,
    302: `Direction = shortest/fastest not applicable`,
    325: `Erroneous array size`,
    326: `Step time = t#0s`,
    350: `Erroneous array size`,
    351: `Step time = t#0s`,
    375: `Erroneous array size`,
    376: `Step time = t#0s`,
    400: `Trigger already active`,
    401: `DriveInterface does not support the window function.`,
    402: `Communication error`,
    410: `Trigger already de-allocated`,
    426: `Invalid velocity or acceleration values`,
    427: `Invalid direction`,
    451: `Invalid velocity or acceleration values`,
    452: `Invalid direction`,
    453: `Direction = fastest not applicable`,
    475: `SMC_ChangeDynamicLimits may only be called in state standstill. or power_off.`,
    476: `Invalid velocity, acceleration, deceleration or jerk values`,
    600: `Cam does not contain any tappets.`,
    601: `Tappet group ID exceeds MAX_NUM_TAPPETS`,
    602: `More than 32 accesses on one CAM_REF`,
    625: `No cam selected`,
    626: `Master axis out of valid range`,
    627: `Velocity and acceleration values must be specified for ramp_in function`,
    628: `Scaling variables fEditor/TableMasterMin/Max are not correct`,
    629: `Too many tappets became active during one cycle`,
    640: `Function block for the given cam format is not implemented`,
    675: `RatioDenominator = 0`,
    676: `Acceleration invalid`,
    677: `Deceleration invalid`,
    678: `Status Enable/Disable of the master has changed without permission`,
    679: `Jerk invalid`,
    725: `Velocity and acceleration/deceleration values invalid`,
    726: `Rotation axis with fPositionPeriod = 0`,
    750: `Type of given cam is not MC_CAM_REF.`,
    751: `Master area, xStart and xEnd, from CamTable is not covered by curve data.`,
    752: `Cam data table has empty master range.`,
    753: `Cam data master has invalid max-, min-values.`,
    754: `Cam data slave has invalid max-, min-values.`,
    775: `During coupling of slave axis, master axis has changed direction of rotation.`,
    776: `Input AvoidReversal is set, but slave reversal cannot be avoided.`,
    777: `Input AvoidReversal must not be set for finite slave axes.`,
    778: `If BufferMode is not Aborting, then MasterStartDistance must not be positive.`,
    779: `The synchronisation cannot be started. This can happen when GearInPos is commanded as a buffered or blending movement and the master is in standstill when it becomes active.`,
    800: `Gear backlash fBacklash too large (> position periode/2)`,
    825: `Internal error: computation of quadratic trajectory failed`,
    826: `Internal error: computation of quadratic trajectory failed`,
    827: `Internal error: computation of quadratic trajectory failed`,
    828: `Internal error: computation of quadratic trajectory failed`,
    829: `Internal error: computation of quadratic trajectory failed`,
    830: `Internal error: computation of quadratic trajectory failed`,
    831: `Internal error: computation of quadratic trajectory failed`,
    832: `Internal error: computation of quadratic trajectory failed`,
    850: `Action only permitted in standstill or power_off.`,
    851: `Invalid ramp type`,
    852: `Action only permitted in standstill or power_off.`,
    853: `Invalid motion type or position period`,
    854: `Function block only applicable to virtual axis.`,
    1000: `Target is not licensed for CNC.`,
    1001: `Path cannot be processed because set velocity = 0.`,
    1002: `Last object of path has end velocity <> 0.`,
    1003: `Warning: GEOINFO-List processed in DataIn but end of list not reached.
Reason:

EndOfList of the queue in DataIn not be set
SMC_Interpolator faster than path generating function blocks`,
    1004: `Velocity at Stop > 0`,
    1005: `Too much SMC_Interpolator recursions. SoftMotion error`,
    1006: `SMC_CheckVelocities is not the last processed function block, that accesses to the OutQueue-data by poqDataIn.`,
    1007: `Internal or numeric error`,
    1008: `Velocity and acceleration / deceleration is null or to low`,
    1009: `FB called with dwIpoTime = 0`,
    1010: `Jerk invalid because jerk must be positive`,
    1011: `Internal error. Computation of the quadratic velocity profile does not converge.`,
    1012: `Invalid velocity mode`,
    1013: `More than the allowed number of axes has been interpolated.`,
    1014: `The segment is numerically degenerate: It is very short and at the end of the queue. It should be ignored.`,
    1015: `Computation of interpolation point failed because the curvature of the spline is too high. Try changing the path to avoid sharp corners.`,
    1050: `Warning: poqDataIn of OutQueue is created too small. Adherence of stops not guaranteed.`,
    1051: `Path does not go completely in queue.`,
    1070: `Direction input has an invalid value.`,
    1071: `Could not determine position on CNC path for the given x-position.`,
    1080: `Warning: poqDataIn of OutQueue is created too small. Adherence of stops not guaranteed`,
    1081: `Warning: Final velocities inconsistent`,
    1100: `Velocity and acceleration/deceleration values non-positive`,
    1120: `Values of fGapVelocity / fGapAcceleration / fGapDeceleration non-positive`,
    1130: `The input has been exhausted, but there is still an unfinished token`,
    1131: `The input does not match any token type`,
    1132: `The input is ambiguous, it could be more than one token type`,
    1133: `The string is too long to be stored in a token. (Too long string literal, variable name or identifier?)`,
    1134: `Invalid number literal.`,
    1150: `Too less arguments provided for function inside G-Code`,
    1151: `Too many arguments provided for function inside G-Code`,
    1152: `Check of argument types matching function declaration returned error`,
    1153: `Could not find local variable on stack`,
    1154: `Could not read string from token`,
    1155: `Got more closing than opening brackets`,
    1156: `Got more opening than closing brackets`,
    1157: `Did not find infix-operator`,
    1158: `Did not find prefix-operator`,
    1159: `Got two operators with equal precedence but non-equal associativity`,
    1160: `Expected a valid term`,
    1161: `Found invalid sequence of tokens inside expression`,
    1162: `Got more terms than expected`,
    1163: `Could not parse an expression because the stack is too small`,
    1164: `The name of a subprogram parameter or variable is already used for a different subprogram parameter or variable.`,
    1165: `The input token queue of the g-code parser does not hold a complete g-code sentence.`,
    1167: `The subprogram declaration could not be stored because the symbol table capacity has been exceeded.`,
    1168: `The maximum number of subprogram parameters has been exceeded.`,
    1169: `The lookup of the subprogram declaration failed. Maybe the subprogram name is incorrect, or the search path for subprograms is incomplete.`,
    1170: `Did not find variable in symbol table`,
    1171: `Token type unknown`,
    1172: `No term after G-address`,
    1173: `Unknown variable type (not LREAL, BOOL, or STRING).`,
    1174: `A token of a different type (e.g. an operator or identifier) was expected here.`,
    1175: `An identifier with length three or longer was expected here.`,
    1176: `The identifier is too long (more than 80 characters).`,
    1177: `A G-address (such as ‘G’, ‘F’, ‘X’) was expected here.`,
    1178: `An N-word (such as ‘N10’) was expected here.`,
    1179: `The sentence number is not in the range [0, ..., 16#FFFFFFFF].`,
    1180: `The sentence number must be a number literal. (For example, expressions are not allowed.)`,
    1181: `The identifier is a reserved keyword that cannot be used here.`,
    1182: `The subprogram declaration has already been read with a different signature or an error.`,
    1183: `The initial value has the wrong type for this local variable`,
    1184: `The maximum number of subprogram parameters has been exceeded.`,
    1185: `A subprogram declaration must be the first sentence in a g-code file.`,
    1186: `Only one subprogram is allowed in a g-code file.`,
    1187: `A LET declaration is not allowed after a regular g-code sentence.`,
    1188: `The END_SUBPROGRAM sentence is not matched by a subprogram declaration.`,
    1189: `After END_SUBPROGRAM, no more tokens are allowed.`,
    1190: `A subprogram is not terminated by END_SUBPROGRAM.`,
    1200: `Acceleration value impermissible`,
    1201: `Deceleration value impermissible`,
    1202: `Data underrun. Queue has been read and is empty.`,
    1203: `Jump to line cannot be executed because line number is unknown.`,
    1204: `Syntax invalid`,
    1205: `Objects are not supported in 3D mode.`,
    1206: `Negative value as a period of additional axes invalid`,
    1207: `Not both axes A and U are interpolated. PA and PU are mutually exclusive.`,
    1208: `Not both axes B and V are interpolated. PB and PV are mutually exclusive.`,
    1209: `Not both axes C and W are interpolated. PC and PW are mutually exclusive.`,
    1210: `For G54/G55/G56, either all of A,B,C or none must be given if orientation mode is not equal to SMC_ORI_CONVENTION.ADDAXES.`,
    1211: `The z-axis of the decoder CS must be equal to the z-axis of the machine CS.`,
    1212: `Scaling would distort commanded circle or ellipse.`,
    1213: `New relative rotation of the DCS (G55) would affect the scaling`,
    1214: `For G54/G55/G56, either all of I,J,K or none must be given.`,
    1250: `Local variable cannot be read due to invalid type`,
    1251: `The variable that’s supposed to be written on does not have the correct type.`,
    1252: `Could not evaluate an expression because the evaluation stack is too small`,
    1253: `Numeric term became NaN`,
    1254: `Division by zero`,
    1255: `Invalid scaling factors`,
    1256: `On subprogram return, the interpreter stack ran empty. Internal error.`,
    1257: `The interpreter stack is too small. Too many local variables in the g-code or too many subprograms active.`,
    1258: `The given buffer for the interpreter stack is either 0 or smaller than 1024 bytes.`,
    1259: `The buffer for the outqueue is too small.`,
    1280: `No data available at all`,
    1281: `Too many different callstacks between current state of interpreter and iObjNo`,
    1282: `Invalid program index`,
    1283: `Too many different programs`,
    1284: `FB called in wrong task`,
    1300: `Buffer too small`,
    1301: `Buffer elements have wrong type.`,
    1302: `Current line of the Interpolator could not be found.`,
    1400: `Internal error in CNC`,
    1401: `The path element cannot hold H Switch points more than MAX_IPOSWITCHES. Adjust the switching points with different ‘O’ values or reduce the number of H points per path element.`,
    1410: `G75 not allowed during tool radius correction`,
    1411: `Queue full, but no further cartesian element`,
    1412: `Tool radius correction does not support movement type SPLINE3D_5`,
    1414: `Plane change not allowed during tool radius correction`,
    1450: `The maximum nesting level for subprogram calls has been exceeded.`,
    1451: `A return statement from the main g-code program is not allowed.`,
    1452: `The declaration of a subprogram has not been found in the subprogram CNC file.`,
    1453: `The next g-code sentence could not be added to the output sentence queue because there was not enough space left.`,
    1500: `Given CNC program is not of type SMC_CNC_REF`,
    1501: `Given OutQueue is not of type SMC_OUTQUEUE`,
    1502: `4-byte aligned buffer part is not used in pbyBuffer`,
    1600: `Function block only works with 2D paths.`,
    1700: `Range for smoothing too large`,
    1701: `Invalid input dSmoothingPart ]0..1]`,
    1800: `SMC_SegmentAnalyzer detects that OutQueue buffer is full but not completed. The function block can only operate when OutQueue fits the buffer completely.`,
    1801: `OutQueue buffer changed while the function block is operating on them.`,
    1820: `Invalid input value in dSplittingParameter`,
    1830: `Position cannot be saved. Interpolator is inactive`,
    1831: `Saved position has not been found so far. It is probably on a different path.`,
    1832: `Structure passed in ePos contains no saved position. SMC_BlockSearchSavePos is not executed or in a wrong way.`,
    1900: `Feature flag must be in the range {1, .., 31}.`,
    1901: `Function block does not support h-functions.`,
    1902: `Function block only works in 3D-Mode.`,
    1903: `Internal error computing the spline.`,
    1910: `wAdditionalParameter is too big`,
    1950: `The value of one of the inputs is invalid.`,
    1951: `The previous movement does not support blending.`,
    1952: `The previous movement does not support buffered movements.`,
    1953: `Cannot inherit owner because the active movement has not been not called yet in this cycle. Internal error.`,
    1954: `The axis is moving but there is no active movement function block. Missing follow-up movement after movement that does not end in standstill?`,
    1955: `The configured BufferMode is not supported by the commanded movement.`,
    1956: `An error occured in a previous movement.`,
    1957: `Only one busy buffered/blending movement per FB instance is allowed.`,
    2000: `File does not exist`,
    2001: `No buffer allocated`,
    2002: `Buffer too small`,
    2003: `Data underrun. Buffer has been read, is empty.`,
    2004: `Placeholder variable could not be replaced.`,
    2005: `Input pvl does not point to a SMC_VARLIST object.`,
    2006: `Input pStringBuffer is not used or does not point to a variable of type SMC_StringBuffer`,
    2007: `In the CNC program more different strings are used than the string buffer can hold.`,
    2008: `The file for a subprogram could not be found.`,
    2050: `File could not be opened.`,
    2051: `No buffer defined`,
    2052: `Buffer too small`,
    2053: `Unexpected end of file`,
    2100: `File could not be opened`,
    2101: `Buffer overrun. WriteToFile must be called more frequently.`,
    2200: `File could not be opened.`,
    2201: `Saved cam too big`,
    2202: `Wrong compilation mode`,
    2203: `File has wrong version`,
    2204: `Unexpected end of file`,
    3001: `This error is obsolete and is maintained only for compatibility. SMC_WDPF_TIMEOUT_PREPARING_LIST`,
    3002: `This error is obsolete and is maintained only for compatibility. File could not be created.`,
    3003: `This error is obsolete and is maintained only for compatibility. Error at reading the parameters.`,
    3004: `This error is obsolete and is maintained only for compatibility. Timeout during preparing the parameter list.`,
    5000: `Nominator of the conversion factor dwRatioTechUnitsDenom of the Encoder reference is 0`,
    5001: `Other module trying to process motion on the Encoder axis`,
    5002: `Filter depth is invalid`,
    6000: `An internal error occurred during initialization of a new movement.`,
    6001: `Invalid axis type, not finite or modulo (internal error)`,
    10000: `Buffer pBuffer too small`,
    10001: `The function block must be applied to a path that fits completely in the buffer.`,
    11000: `The axis group is in the wrong state for the requested operation.`,
    11001: `More than the maximum allowed number of axes has been added to an axis group.`,
    11002: `The dynamic limits of a single axis are invalid. (fSWMaxVelocity/Acceleration/Deceleration/Jerk)`,
    11004: `The given coordinate system is invalid for the requested operation`,
    11005: `An axis of the axis group is in state error`,
    11006: `The given buffer mode is not supported`,
    11007: `The dynamic factor is not in the range ]0 .. 1]`,
    11008: `The dynamic limits for the movement are invalid.`,
    11009: `The given axis is not part of the axis group.`,
    11010: `The requested operation is not supported`,
    11011: `No kinematic configuration has been configured.`,
    11012: `The number of axes is not equal to the number of axes needed by the kinematic transformation`,
    11013: `A coordinated movement has been interrupted by a single axis movement.`,
    11014: `An error occurred while following the computed set values.`,
    11015: `An axis group cannot depend on more than one master axis group.`,
    11016: `An axis group A may not depend on another axis group that depends on A.`,
    11017: `A dependant axis group must be executed in the same task.`,
    11018: `An axis belonging to an axis group must be executed in the same task.`,
    11019: `A second activation of the function block occurred while the PCS was still used by buffered motion commands.`,
    11020: `An error ocurred in a previous motion command.`,
    11021: `A parameter of an administrative function block is invalid.`,
    11022: `One of the axes of the group uses an unsupported ramp type. Only trapez and quadratic are supported.`,
    11023: `invalid transition parameter`,
    11024: `Internal error in the state machine of the axis group.`,
    11025: `CP-Tracking: Cannot keep the path; try to reduce the dynamics on the path and / or the dynamics when entering CP-Tracking.`,
    11026: `current position does not allow continuation.`,
    11027: `Buffer in continueData is too small; big external movement-queue-buffer in use.`,
    11028: `The checksum stored in the continue data is wrong. The continue data either was not written by MC_GroupInterrupt, or was modified afterwards.`,
    11029: `Commanded SMC_GroupWait while axes were moving independently from the axis group (single axis movement or similar).`,
    11030: `Inverse transformation lead to axis values exceeding the configured limits.`,
    11031: `Prohibit adding the same axis to an axis group twice`,
    11032: `No transformation is set.`,
    11033: `The path cannot be resumed after the current axis group error.`,
    11034: `The continue data for MC_GroupContinue has not been written correctly. (MC_GroupInterrupt not called / non-resumable axis group error)`,
    11035: `The configured kinematics does not support ABC_As_ACS`,
    11100: `Internal error in the kernel`,
    11101: `Task cycle time not positive`,
    12000: `The parameter values of the transformation are invalid.`,
    12001: `The requested position is outside of the working area of the transformation.`,
    12002: `The tool cannot work together with the positioning-part of the machine. Either, the positioning-part doesn’t implement ISMPositionKinematics2, or the tool cannot deal with the positioning’s image of orientations.`,
    12003: `The FB implements |ISMKinematicWithInitialization|, but hasn’t been Initialized yet.`,
    12004: `Special error for positioning part of Kin_4Axis_Palletizer, which implements ISMPositionKinematics_Offset2, but cannot actually cope with offsets <> 0.`,
    12005: `The configured tool offset is not compatible with the kinematics used`,
    12100: `The cache of the CP planner is too small.`,
    12101: `The evaluation of the position on a path element failed (internal error).`,
    12102: `Non-continuable state reached (internal error).`,
    12103: `Maximum trajectory length exceeded (internal error).`,
    12104: `Path acceleration too high (invalid state, internal error).`,
    12105: `Maximum number of iterations exceeded (internal error).`,
    12106: `No trajectory could be computed (internal error).`,
    12107: `The out-queue is full (internal error).`,
    12108: `Queue underrun: no element left in queue.`,
    12109: `Invalid queue (invalid size or pointer)`,
    12110: `An internal error occurred while blending two CP movements`,
    12111: `The three points that define the circle are collinear.`,
    12112: `The center point is not on the perpendicular bisector of the start and end point.`,
    12113: `The radius is zero`,
    12114: `The distance between start and end point is larger than the diameter. (When trying to create a circle using SMC_Circ_Mode.Radius.)`,
    12115: `The start and end point are equal (SMC_Circ_Mode.Radius).`,
    12116: `The blending spline is degenerate (too short or non-regular)`,
    12117: `The path element cannot be created because it is too short.`,
    12118: `The path could not be cut for aborting movement (internal error).`,
    12119: `The given angular velocity or acceleration is invalid (quaternion with non-zero real part, internal error).`,
    12120: `The given orientation is invalid (non-orthonormal matrix or non-unit quaternion, internal error).`,
    12121: `The given time budget for the computation is exceeded (internal error).`,
    12122: `A limit of an axis has been violated. This can happen if a CP movement is done too close to a singularity or if the path has a very high curvature.`,
    12125: `The kinematic configuration of the start position differs from the end position. The CP movement would pass a singularity.`,
    12126: `This error is obsolete and is maintained only for compatibility. If a CP-halt/-stop is commanded, some information has to be transferred to the bus task. We expect this to happen before the next cycle of the slow task.`,
    12127: `The stop trajectory could not be found in the interval. (internal error)`,
    12128: `The kinematics does not support the orientation mode “Axis” for continuous path movements.`,
    12129: `The axis orientation interpolation mode is not supported for CP movements with a dynamic PCS (tracking).`,
    12130: `An invalid path element has been created (internal error)`,
    12131: `The transition between two path elements is not G2 continuous, and there is no stop (internal error)`,
    12132: `Axis orientation interpolation mode is used, but between the start end end position, there is a singularity of the position kinematics.`,
    12133: `The position kinematics has configurations but does not implement the interface ISMPositionKinematics_Offset2. In this case, axis orientation interpolation is not possible.`,
    12134: `The target position of a rotary axis will not be reached in the commanded period. (E.g. the commanded target position is -170°, but the target will be reached with position 190° instead.) This means that the chosen interpolation to the target position is not compatible with the commanded position.`,
    12135: `A rotary axis has violated the allowed axis range during a CP movement. The CP movment is not in the working area.`,
    12136: `The target trajectory could not be computed due to a discontinuity of the end position (internal error).`,
    12137: `The trajectory is not smooth, the phase end states do not equal the the current state (internal error).`,
    12138: `A parameter transformation could not be created (internal error).`,
    12139: `Error generating path-invariant PTP element (internal error).`,
    12140: `Error while computing a new trajectory: the path velocity after phase 1 (positive jerk of length dTau1) is negative (internal error).`,
    12141: `Transitioning from a single axis movement to a continuous path movement is not supported.`,
    12142: `The CP-planner did not make any progress. This is an internal error That can be triggered by very sharp corners (e.g. blending between short elements or with small corner distance).`,
    12143: `Internal error in the evaluation cache of the CP-planner.`
}

export { smc_errors }